- hosts: "*"
  tasks:
    - name: install git curl wget
      pacman:
        name:
          - git
          - curl
          - wget
          - docker
        state: present
        update_cache: true
      become: true

    - name: install neofetch neovim tmux nodejs go fd bat ripgrep jq lazygit autojump docker docker-compose htop
      community.general.homebrew:
        name:
          - neofetch
          - neovim
          - tmux
          - nodejs
          - go
          - fd
          - bat
          - tldr
          - ripgrep
          - jq
          - lazygit
          - autojump
          - docker
          - docker-compose
          - htop
        state: present
